apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: urayoko/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src:  'src/**/*.ts'
            dest: .
    - image: urayoko/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src:  '**/*.js'
            dest: .
    - image: urayoko/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src:  'src/**/*.ts'
            dest: .
    - image: urayoko/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src:  'src/**/*.ts'
            dest: .
    - image: urayoko/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src:  'src/**/*.ts'
            dest: .
    - image: urayoko/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src:  'src/**/*.ts'
            dest: .